### PR TITLE
Lint JS using JSHint, automatically lint using Travis CI

### PR DESCRIPTION
**Pull request by frewsxcv**

### CODE REVIEW

**Comment by frewsxcv** [comment]
It'll be easier to see the changes in the diff via https://github.com/rust-lang/rust-playpen/pull/108/files?w=1

**Comment by frewsxcv** [comment]
Also in case this does get merged and Travis CI is desired, make sure to enable it for this repository

**Comment by alexcrichton** [comment]
Awesome, thanks!

**Comment by alexcrichton** [comment]
Ah looks like the build is failing though due to it picking up the JS files in `node_modules` as well :(

**Comment by alexcrichton** [comment]
er, example here: https://travis-ci.org/rust-lang/rust-playpen/builds/63259234

**Comment by chris-morgan** [comment]
Ick, two spaces for the first, superfluous level of indentation and then four spaces? Most text editors won’t cope well with that.

**Comment by chris-morgan** [comment]
This has made harmful changes:

```diff
-result.parentNode.offsetHeight;
+// result.parentNode.offsetHeight;
```

This change is BAD. Accessing `offsetHeight` is not a noop but can rather trigger repaint, as I would have thought JSHint should know.

**Comment by huonw** [comment]
Is there a way to trigger a repaint where it is clear that something non-trivial might be happening?

**Comment by chris-morgan** [comment]
@huonw: that’s what the comments are for. Any frontend developer worth their salt will recognise the technique, too. One could also shift the next line into a `setTimeout(function() { … }, 0)`, but that approach is uglier. There are no clearer ways of doing it that I am aware of.

**Comment by frewsxcv** [comment]
@chris-morgan There is no comment explaining that calling a getter has unintended side-effects. For what it's worth, i do a fair amount of frontend development and have never encountered this pattern.

**Comment by frewsxcv** [comment]
I'll open a PR with a fix.

**Pull request merged**
