### PR TITLE
Detect tests and treat them as tests, not main.

### PR DESCRIPTION
**Pull request by chris-morgan**
See #107 and #32 for some other discussion of this concept.

This approach doesn’t deal with every situation, as it detects a program as either for execution or for testing, but it deals with the most common situation more elegantly than any other approach.

As usual, this code is running at http://temp.chrismorgan.info/rust-playpen/static/web.html, but the actual test functionality won’t work because it’s using play.rust-lang.org for execution and so it doesn’t have the necessary server changes to support it.

### CODE REVIEW

**Comment by chris-morgan** [comment]
cc @badboy @huonw

I’ll rebase this after #110 lands.

**Comment by brson** [comment]
lgtm. waiting on rebase

**Comment by chris-morgan** [comment]
Rebased; http://temp.chrismorgan.info/rust-playpen/static/web.html updated too, same caveats as before.

**Comment by badboy** [comment]
I actually like this over my own PR (#107).
It should do the right thing™ for most people out-of-the-box without adding anymore settings.

**Pull request merged**
