### PR TITLE
Update Ace to 1.2.6

### LINKED ISSUE #201: Identifiers ending with digits are highlighted as 2 separate parts.
If an identifier ends with a digit (not followed by any letter or underscore), the digit is highlighted separately from the rest of the identifier.

_Also, slightly unrelated request: the keywords 'mut' and 'self' being the same color as all others in the middle of code is a worse situation that it'd been before ('self' and 'mut' were turquoise in Monokai, while now they're the same red shade as all others)._

### PR DESCRIPTION
**Pull request by TimNN**
This includes the identifiers ending in numbers fix (ajaxorg/ace#3083) as well as highlighting for `i/u128` (ajaxorg/ace#3153).

Fixes #201.

The integrity hashes were generated from https://github.com/ajaxorg/ace-builds.

(I wasn't sure about committing the lock file changes, so I kept them in a separate commit which can easily be removed, if desired)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Looks good to me! Want to ping me whenever the blocking issue is resolved and I'll merge/deploy?

**Comment by TimNN** [comment]
> Want to ping me whenever the blocking issue is resolved?

Sure, will do.

**Comment by TimNN** [comment]
@alexcrichton: This is good to go now, the blocking PR has been merged (and the cdn updated: https://cdn.jsdelivr.net/ace/1.2.6/min/ace.js).

**Comment by solson** [comment]
I believe this is the cause of https://github.com/rust-lang/rust-playpen/issues/262. Can we roll it back to fix the regression in usability and re-apply once we have a way to disable quote auto-matching?

If someone knows how to fix the latter trivially, that's great, too, but it's better not to wait around while usability has regressed. I started looking into it but I don't know JS. :(

**Comment by alexcrichton** [comment]
@solson yeah that sounds good to me, want to send a PR?

**Comment by solson** [comment]
@alexcrichton Done, at https://github.com/rust-lang/rust-playpen/pull/264.

**Comment by solson** [comment]
Tracking the re-application of the original update in https://github.com/rust-lang/rust-playpen/issues/265.

**Pull request merged**
