### PR TITLE
Fix playbot-mini

### LINKED ISSUE #221: playbot-mini appears to be broken
```
20:29 <@acrichto> playbot-mini: fn main() {}
20:29 -playbot:#rust-internals- <anon>:10:19: 10:23 error: expected `(`, found `main`
20:29 -playbot:#rust-internals- <anon>:10         -mini: fn main() {}
20:29 -playbot:#rust-internals-                             ^~~~
20:29 -playbot:#rust-internals- (output truncated; full output at 
          http://bit.ly/28MrdBa)
```

### PR DESCRIPTION
**Pull request by jonas-schievink**
Closes #221

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Would it be possible to add a test for this perhaps?

**Comment by jonas-schievink** [comment]
Not without significant restructuring or using `irc`s `MockConnection` which means I'd have to dive into the IRC protocol itself :/

**Comment by alexcrichton** [comment]
Hm ok

**Pull request merged**
