### PR TITLE
Show an alert before unload the page

### PR DESCRIPTION
**Pull request by fcsonline**
If you are playing with Rust and you leave accidentally the page you will
lose all your work if you have not save it. This could be annoying. Just
show an alert to confirm that.

### CODE REVIEW

**Comment by alexcrichton** [comment]
This seems like if we want the alert it may want to be a bit more targeted than any page unload. For example if no text was edited or the page has been idle for awhile, it may just be annoying to pop up this warning?

**Comment by fcsonline** [comment]
Totally agree. I'm modifying it just to add this handler if the text was edited. About if the page was idle for a while, I think that is not a good idea and could be treated as an unexpected behaviour.

**Comment by alexcrichton** [comment]
I guess one thing I worry about here is that I wouldn't want to see the dialog if I'm done with what I'm doing on play and then try to close it. If a false positive shows up it can be pretty annoying. Along those lines I'm not sure that we can actually get rid of false positives here, for example there are situations like:

* I edited some code, ran it, and then closed the window.
* I edited some code, didn't run it, realized my mistake, then closed the window
* etc.

**Comment by enricostano** [comment]
One of the root causes of this IMO is that clicking on play button moves the focus out of the code textarea. Then if you hit a key like backspace (thinking that you're still editing the code) some browser will land you back in the browser history. Maybe a first improvement would be to restore the focus to the code area after compiling and showing the result.

**Comment by fcsonline** [comment]
Ok, then due the number of false positives that this handle can have, should we close this PR?

**Comment by alexcrichton** [comment]
Ok, sounds like a plan to me.

**Pull request closed without merging**
