### PR TITLE
ASM, LLVM-IR and MIR buttons set --crate-type=lib

### PR DESCRIPTION
**Pull request by nodakai**

### CODE REVIEW

**Comment by alexcrichton** [comment]
Could you elaborate on why? It'd be good to have some motivation to go along with changes like this as well.

For example one downside of this is that you now have to somewhat surprisingly write `pub` in front of all functions that you want to see disassembly for in optimized code?

**Comment by jonas-schievink** [comment]
@alexcrichton The main motivation is that you no longer have to put an `fn main` in there for it to compile

**Comment by nodakai** [comment]
I should have mentioned #124

@alexcrichton Good point, but some of those cases may be covered by a single `pub` to `main()` (and it doesn't seem to hurt even for the exe-producing mode.) What are other major drawbacks?

My original idea was adding a checkbox but I began to worry some people might not have a screen that is wide enough for the growing number of config items.

**Comment by alexcrichton** [comment]
I'm getting somewhat wary of the what seems to be dozens of tips and tricks the playpen does today. There's all sorts of "if you do this we do that automatically" pieces of logic here and there, and without any tests or documentation this becomes very difficult to keep up with.

To me it's much more straightforward to understand how it works (it just compiles without flags) and then work with that

**Comment by nodakai** [comment]
> There's all sorts of "if you do this we do that automatically" pieces of logic here and there

1. If the code contains `#[test]` but not `fn main()`, then the [Run] button is renamed to [Test], the compiler is run with `--test` and the output executable with `--color=always`
2. The [MIR] button changes the channel to nightly (out of kindness; you may find it acceptable to let the stable compiler fail.)
3. My patch is adding `--crate-type=lib` for [ASM], [LLVM IR] and [MIR]
4. Also, [Debug] means `-C opt-level=0 -g` and [Release] `-C opt-level=3`, if you count them as the automagicals.

There is a firm need for checking how a single function (sometimes as a proxy for a single expression) is compiled and we should officially support such a usage, where "support" means something more than "leaving non-zero possibility for it"

Besides, I won't be surprised if the `crate_type` attribute is removed from the language given the project's ever increasing dependency on Cargo and that the attribute is inherently hackish.

**Comment by alexcrichton** [comment]
You can already do these kinds of checks with `#![crate_type]` or a small `fn main`, so I'm less convinced that we need another vector to do so. I also think that the difference of `pub` and reachability for libraries can be a source of confusion because optimized assembly will output nothing unless you have `pub` functions, and then when you run it the `pub` annotations are all unnecessary.

**Pull request closed without merging**
