### PR TITLE
A couple fixes from my previous pull request

### PR DESCRIPTION
**Pull request by frewsxcv**
A couple issues were brought up in https://github.com/rust-lang/rust-playpen/pull/108

### CODE REVIEW

**Comment by frewsxcv** [comment]
Ignore whitespace diff

https://github.com/rust-lang/rust-playpen/pull/110/files?w=1

**Comment by chris-morgan** [comment]
LGTM.

**Comment by brson** [comment]
Thanks!

**Comment by brson** [comment]
Deployed.

**Pull request merged**
