### PR TITLE
Rejig the web interface substantially.

### PR DESCRIPTION
**Pull request by chris-morgan**
Notable changes:

- It doesn’t look especially ugly any more (slightly subjective!);
- The interface is all clearer;
- Suitable title attributes have been added everywhere;
- The vertical scaling of the interface is fixed so it works at all realistic sizes (as far as widths is concerned, it scales down to about 700px wide and gets slightly broken after that);
- Output is handled better (e.g. when running code, rustc output appears in a different colour to that of the program execution);
- Error messages are explained further;
- With Vim keyboard bindings, :w is hooked up to run the code.

Still TODO is tiling input and output horizontally for wide enough viewports. It will come.

I have a copy of this running at http://temp.chrismorgan.info/rust-playpen/static/web.html.

### CODE REVIEW

**Comment by mkpankov** [comment]
A thing that keeps confusing me: "application terminated with error code 101" is shown when either the compilation failed, or the program itself panicked during run time. Maybe it's possible to differentiate the two?

Good work overall :+1:

**Comment by chris-morgan** [comment]
@mkpankov I improved it a little over the status quo by changing the colour of the rustc output. I contemplated adding labels “Compiler output” and “Program output”, but decided to leave them out for now and review the situation later. It’s more a feature request, really.

**Comment by mkpankov** [comment]
@chris-morgan Ok, I agree

**Comment by mkpankov** [comment]
@chris-morgan for some reason, hitting "format" in the hosted version makes the code one-line.

**Comment by chris-morgan** [comment]
@mkpankov The rustc pretty printer is fairly dodgy these days. That’s not my responsibility, though—it’s not changed from play.rust-lang.org’s current behaviour.

**Comment by mkpankov** [comment]
@chris-morgan yeah, right. Was surprised simple two-line program can throw it off.

**Comment by pkondzior** [comment]
It would be cool if #result and #editor splitter allow vertical resizing of each of the containers.

**Comment by jpoehls** [comment]
Really like the improvements here. Would be good if it handled small screens better, particularly for mobile use.

screenshot_051315_082153_am

**Comment by chris-morgan** [comment]
@pkondzior: that’s a good idea, and something I may well do in the future. As it stands, it matches the previous division, except it does it properly, which I feel to be sufficient for the 1.0.0 release preparations.

As noted, I also intend to use a horizontal split for wider screens in future, so it will become a less important consideration.

**Comment by chris-morgan** [comment]
@jpoehls: known issue (as noted, it works down to about 700px), mitigated by the fact that mobile browsers apply scaling so that the viewport is actually not narrow. Of course, that also means that the text tends to be tiny, but you can’t win them all when you’re trying to avoid depending on flexbox for the basic layout for browser compatibility reasons. (That’s a temporary measure; I will be depending on it soon, this is more a stopgap page layout technique.)

**Comment by jpoehls** [comment]
I noticed the Rust logo PNG is ~131 KB. Could probably trim the down quite a bit by switching to the SVG logo. http://www.rust-lang.org/logos/rust-logo-blk.svg

**Comment by chris-morgan** [comment]
The logo technique I took for speed from what I did with http://arewewebyet.com/; it needs, at the least, rotating and trimming to size, cutting out the hidden parts and transforms.

We also need to decide whether the colour logo is shown a grave. Should I go with the black logo (either black or brown), or with the colour logo?

**Comment by chris-morgan** [comment]
You can try the black version of the logo out by adding these styles:

```css
:root::before {
    content: "";
    top: -214px;
    right: -222px;
    width: 690px;
    height: 690px;
    opacity: 0.35;
    background-image: url("http://www.rust-lang.org/logos/rust-logo-blk.svg");
    background-size: 100%;
}
```

Naturally if actually making the change I will be more precise and will slice and dice the SVG.

**Comment by chris-morgan** [comment]
One other change I forgot to mention is that I’ve rebranded the playpen to a playground. I personally prefer the latter to the former, but this is definitely negotiable.

**Comment by jpoehls** [comment]
> I’ve rebranded the playpen to a playground

:+1: 

I do prefer the black version of the logo. It's a minor difference but I prefer the flatter look since it shouldn't be a visual focal point on the page.

I'll go ahead and throw out that I'm not a big fan of the Settings button right now. I think a few things are standing out to me:

1. Seems smaller than the other buttons (height wise).  Could be an illusion due to positioning and width.
2. It's the only button using the brown on white coloring. Might try using the same white on brown coloring that the Run button uses? Or replace the gear icon with a text label "Settings" which would match the Format and Share buttons but sacrifice a bit of space.

**Comment by alexcrichton** [comment]
This looks amazing, really nice work @chris-morgan! 

Is this ready to go or do you have a few more changes you'd like to queue up before landing? Everything looks good to me so I'd be fine landing ASAP :)

**Comment by chris-morgan** [comment]
@jpoehls: the settings button *is* smaller than the others, deliberately so. It’s also minor, where white on red/brown is to draw focus. I tried blacks/greys on white too but didn’t come up with anything that felt right, and so though the reds it has at present also don’t feel completely right they feel closer to right than anything else I’ve tried.

@alexcrichton: I have now made all the changes that I think are *necessary* at this stage. Feel free to merge.

**Comment by alexcrichton** [comment]
Awesome, thanks again @chris-morgan!

**Comment by yazaddaruvala** [comment]
Hey @chris-morgan, it looks really cool, thanks!

One issue: I can't actually close the output console and it sort of blocks most of the editor.

I'm not sure what my companies stance would be on contributing or I'd do it myself, but I think you just need: `#editor { ...; overflow-y: auto; }`

Potentially even a close button somewhere on the output console to give back screen real-estate.

**Comment by chris-morgan** [comment]
@yazaddaruvala I implemented a close button on the output console half an hour ago (not yet landed, but visible at http://temp.chrismorgan.info/rust-playpen/static/web.html). I don’t reproduce what you describe as far as the output pane blocking most of the editor is concerned; can you give more details of browser environment and viewport dimensions?

**Comment by yazaddaruvala** [comment]
@chris-morgan thanks for the close button!

This is no longer an issue with the close button, but since you asked, here is the additional info:
MacBook Pro Retina 13in - Chrome (Fullscreen)

Screenshots:
[Without the console output](http://i.imgur.com/hrkEVS8.png)
[With the console output](http://i.imgur.com/MhBFjTE.png)

Hopefully, that is more clear

**Comment by chris-morgan** [comment]
@yazaddaruvala I figured out the problem; a fix is waiting in #96.

**Pull request merged**
