### PR TITLE
don't print version for playpot

### LINKED ISSUE #253: Playbot outputting rustc version
Looks like this recent commit https://github.com/rust-lang/rust-playpen/commit/320e9aa86b940c97dd32d8689d6b5b9e0c152121 now causes `playbot` to *always* output the version, which is unnecessary and just adds noise.

```
[17:17:57]  <dikaiosune>	playbot: '#'
[17:18:00] -playbot-	rustc 1.11.0 (9b21dcd6a 2016-08-15)
[17:18:00] -playbot-	'#'
```

### PR DESCRIPTION
**Pull request by TimNN**
Fixes #253.

r? @alexcrichton

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks!

**Comment by alexcrichton** [comment]
Hm I think I've deployed this, but it appears to persist?

**Comment by TimNN** [comment]
Did you manually rebuild the docker images? Otherwise we'll need toneait for the cronjob to kick in.

**Comment by TimNN** [comment]
The environment variable is at least, see `/msg playbot ::std::env::var("RUST_PLAYPEN_ENV")`.

**Comment by alexcrichton** [comment]
Aha, good point! They'll auto-rebuild in the morning so that should take care of itself.

**Pull request merged**
