### PR TITLE
re-add backtrace functionality

### LINKED ISSUE #229: The Backtrace setting has no effect
Try running [this code](https://play.rust-lang.org/?code=fn%20main()%20%7B%0A%20%20%20%20fn%20diverges()%20-%3E%20!%20%7B%0A%20%20%20%20%20%20%20%20panic!(%22This%20function%20never%20returns!%22)%3B%0A%20%20%20%20%7D%0A%20%20%20%20diverges()%3B%0A%7D&version=stable&backtrace=1)

You get the message: `note: Run with RUST_BACKTRACE=1 for a backtrace.`
even though the Backtrace setting is `on`

### PR DESCRIPTION
**Pull request by TimNN**
Fixes #229

(I'm not really sure about the usefulness of the `auto` setting, but kept it for compatibility with the previous implementation.)

### CODE REVIEW

**Comment by alexcrichton** [comment]
Thanks! Looks like CI needs some fixing though?

**Comment by TimNN** [comment]
Should be fixed now. (Tests and playbot needed to be updated as well...)

**Comment by alexcrichton** [comment]
Thanks!

**Pull request merged**
