### PR TITLE
Updated Ace used to version 1.2

### PR DESCRIPTION
**Pull request by Enamex**

### CODE REVIEW

**Comment by alexcrichton** [comment]
What features are we picking up from this? Also, are you sure no apis changeD?

**Comment by mcast** [comment]
On Thu, Jul 23, 2015 at 10:00:21PM -0700, Alex Crichton wrote:

> What features are we picking up from this? Also, are you sure no
> apis changeD?

Something which would increase the value of this for me is a pointer
to the correct documentation.

For #143 I found [enough documentation](http://ace.c9.io/#howto=&nav=api&api=selection)
to get the job done, but it described functions which are not in 1.1.9
so my PR is...  possibly not using Ace correctly.

-- 
Matthew


-- 
 The Wellcome Trust Sanger Institute is operated by Genome Research 
 Limited, a charity registered in England with number 1021457 and a 
 company registered in England with number 2742969, whose registered 
 office is 215 Euston Road, London, NW1 2BE.

**Comment by Enamex** [comment]
Not sure how to quote users here but anyway ;)

The only thing I *intended* as an addition in updating to Ace 1.2 is the changed highlighting rules for Rust. I'm not sure what else that's changed is relevant to Playpen's use.

That said, I admit I haven't checked whether the merged changes have made it to version 1.2 or are bound to a later ver :/

**Comment by mdinger** [comment]
I would hold off on this. That regex change messed up commenting highlighting in [rustbyexample.com](http://rustbyexample.com/) (see https://github.com/rust-lang/rust-by-example/issues/619). It was fixed in https://github.com/ajaxorg/ace/pull/2600 but until it makes it to a release rustbyexample is using a locally fixed version: https://github.com/rust-lang/rust-by-example/pull/620. Merging would probably force playpen to do something similar too.

**Comment by Enamex** [comment]
Weird. The specific reason mentioned (that `//` is treated as an operator) wasn't in anything I'd changed (only operators I'd included in the regex where single-glyph and `/\|\||&&|->|==/` and the assignment ones, only :/

**Comment by mdinger** [comment]
Eh, the problem with this regex is it's kinda repetitive and a lot of it doesn't do anything helpful and isn't obvious:
```text
 /[$]|->|--?|\+\+?|==?|<<=|>>=|[<>]=?|[&]{2}|[|]{2}|[$]|[|!&^*\-+%/]=?/

// This part has a few issues:
[|!&^*\-+%/]=?

1. `\-+` is a range starting with `\` and ending with `+` which probably wasn't
the intent. The class should be `[-|!&^*\+%/]` to avoid the range.
2. For every character in the bracket, these will all be valid matches:
++=
^   match
 ^  match
 ^^ match

Even longer sets will match:
++=*//%=
^          match
 ^         match
 ^^        match
   ^       match

// duplicated
++=*//%=
    ^      match
     ^     match
      ^    match
      ^^   match

Meaning `\+\+?` and all the stuff at the beginning is duplicated.
`/` (divide) `//` (comment, `//=` (invalid), `/*` and `*/` are also
all blocked.
```

The way you avoid this is with both [positive and negative look-around assertions](http://perldoc.perl.org/perlre.html#Extended-Patterns) which most regex don't support (javascript only supports forward it seems). Look-around allows you to say "I'm looking for `++` which isn't either followed or preceded by a `+` but may be followed by a `?`.

**Comment by alexcrichton** [comment]
OK, sounds like we should hold off on merging for now according to @mdinger, so I'm going to close.

**Pull request closed without merging**
