### PR TITLE
Add support for intel syntax when emitting asm

### PR DESCRIPTION
**Pull request by richo**
Confirmed that `-C llvm-args=-x86-asm-syntax=intel` is harmless when emitting IR.

### CODE REVIEW

**Comment by brson** [comment]
This is deployed but the UI looks strange. The option box is just sitting next to 'Themes'.

**Comment by richo** [comment]
Oh, I think I goofed when I committed. Sorry, let me fix it up real quick
and PR again.

**Comment by brson** [comment]
@richo JS also generates errors when clicking ASM and LLVM IR now.

**Comment by richo** [comment]
Yup, I massively fat fingered an add -p, fixing now

**Pull request merged**
