### PR TITLE
Add a Pygments lexer for MIR output, and fix HTML escaping.

### PR DESCRIPTION
**Pull request by birkenfeld**
Also fixes the problem of insufficient HTML escaping of MIR output
by neither highlighting nor escaping it.

### CODE REVIEW

**Comment by jonas-schievink** [comment]
This is going to be... interesting to rewrite in Rust for #187

**Comment by birkenfeld** [comment]
Well, as it happens I was just beginning to port parts of Pygments to Rust. I could probably have a version with the three lexers in question ready pretty soon.

**Comment by birkenfeld** [comment]
Regardless, could the escaping bug be fixed now at least? It is actively hurting readability of the MIR output.

**Comment by jonas-schievink** [comment]
Oh, please don't hold back features because of the rewrite. I'm fine with either waiting for your Pygments port or writing a temporary highlighter for #187.

**Comment by alexcrichton** [comment]
Thanks @birkenfeld! Sounds reasonable to merge for now and tackle in the rewrite in #187 later.

@jonas-schievink also I still hope to get around to taking a closer look soon, sorry it's taking awhile :(

**Comment by alexcrichton** [comment]
Ah unfortunately it looks like this breaks the MIR button as it also requires some JS changes, perhaps those could be prep'd as well?

**Comment by birkenfeld** [comment]
Sorry - looks like I'll have to set up a local instance after all. Stand by...

**Comment by NotaseCretagen** [comment]
(Side note: Thanks Alex for restarting play-pen, I've been waiting for that feature when you press Esc key after clicking Run button, to kick in for a while now :D)

**Comment by alexcrichton** [comment]
@NotaseCretagen oh oops! Feel free to ping me if it ever needs a restart and I'm not getting around to it

**Pull request merged**
