### PR TITLE
Add possibility to add locally stored templates

### PR DESCRIPTION
**Pull request by panicbit**

### CODE REVIEW

**Comment by panicbit** [comment]
A preview is available [here](https://rawgit.com/panicbit/rust-playpen/9a8dcbebc11ba8e2efe594f13207dbbbdcb3a3b0/static/web.html).
I'll fix the lint errors in a minute.

**Comment by mcast** [comment]
I like the rawgit trick, should try it on my (old stale) PR - thanks.

Tried your link, I see the new Templates button (after a false start with it pointing to some other commit(?)), but Firefox console says "SecurityError: The operation is insecure." at `web.js?10:469:0` when I click it.  I'm not sure what I should do to enable localStorage.  I have NoScript and RequestPolicy plugins.

**Comment by panicbit** [comment]
@mcast It works fine her using NoScript. What kind of RequestPolicy plugin do you use?
As far as I can tell this should only trigger in a cross-domain situation (whcich doesn't apply here). I guess the problem might be that your RequestPolicy plugin blocks access to localStorage?

**Comment by mcast** [comment]
RequestPolicy is https://www.requestpolicy.com/ and I see no mention of or settings for localStorage in its preferences, nor NoScript's.
[This](https://github.com/tysonmatanich/elementQuery/issues/10) sounds relevant.  I'm using Firefox 38.2.1, with a corporate configuration which I think is fairly minimal.

**Comment by mcast** [comment]
From the js console, I see that `localStorage.length` is insecure on various sites include duckduckgo.com and metacpan.org; but it works on the local Confluence site and github.com front page.

**Comment by panicbit** [comment]
@mcast Hm, there's a way to avoid using `localStorage.length` to store the templates but it's a bit annoying.

**Comment by panicbit** [comment]
[Updated demo.](https://cdn.rawgit.com/rust-lang/rust-playpen/1e47d938e170cdd41fe1f833de79b7cfcd1cd15e/static/web.html)
@mcast Can you please check if your issue is resolved in this version?

**Comment by mcast** [comment]
I was only using `.length` to exercise it, I suspect it was the access to `localStorage` itself which was the security problem.  From the console,
```
09:44:58.781 l = localStorage
09:44:58.785 SecurityError: The operation is insecure.
```

On 1e47d93 I get the "Templates // Here you can create a library of templates that is stored locally on your computer." widgets, but nothing happens (not even an error) when I give a name and click Create.

**Comment by panicbit** [comment]
[Updated demo (2748800).](https://cdn.rawgit.com/panicbit/rust-playpen/2748800e98b699e3928c5693080e6f323e425497/static/web.html)

The templates button won't show now if localStorage isn't available.

**Comment by mcast** [comment]
I found it - sorry it's a bit late.  [Have to enable cookies.](http://stackoverflow.com/questions/10516767/access-of-local-storage-giving-security-error-after-cookies-are-disabled-in-fire)

Unfortunately, attempting to access localStorage doesn't pop up the "should I accept the cookie" dialog the way HTTP cookies do.  Now I manually enabled them for rawgit.com, the feature works.

**Comment by alexcrichton** [comment]
Thanks for the PR @panicbit! Could you elaborate a bit more on the use case for this? I'm a little wary to add lots of bells and whistles to play.rust-lang.org as it unfortunately doesn't have a consistent maintainer and has very few tests, so it's likely for features like this to break over time if they're not heavily used :(

**Comment by panicbit** [comment]
@alexcrichton 
- A user might want to reset the code buffer to some state. Typing out skeleton code gets annyoing with time (IMO).
- A user might want to save the code buffer to show it to someone later. Anonymous gists already somewhat fulfill this use case bu have the disadvantage that have to keep track of the gist url somewhere. Using non-anonmous gists have the disadvantage of requiring the user to pull up another tab/window and manually copy&paste the code.

**Comment by alexcrichton** [comment]
Hm ok, I feel like that may be a bit at odds with the design of the playpen, however. We're not necessarily trying to be a full-on IDE or anything like that, but rather a quick-to-use tool that's not necessarily persistent everywhere. With that model templates seem to me like they don't quite fit into the model unless we have something like user accounts which we're very unlikely to do just yet.

**Comment by panicbit** [comment]
Feel free to close this then. If people really want to use this feature
they can use the rawgithub version anyway :)

Alex Crichton <notifications@github.com> schrieb am Mo., 14. Dez. 2015
17:41:

**Comment by alexcrichton** [comment]
Ok, in that case I'll close this for now, but thanks regardless @panicbit!

**Pull request closed without merging**
